import { Restaurant } from './list/list.tsx';


export const list: Restaurant[] = [
  {
    id: '1',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [
      { id: '국밥', name: '국밥' },
      { id: 'good', name: 'good' },
      { id: 'nice', name: 'nice' },
    ],
    score: 3,
  },
  {
    id: '2',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '3',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '4',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '5',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '6',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '7',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '8',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '9',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '10',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '11',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '12',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '13',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
  {
    id: '14',
    name: '유미카츠 잠실점 (새로 오픈)',
    description: '적당히 먹을 만해요',
    authorId: 'tjalsdud89',
    tag: [{ id: '국밥', name: '국밥' }],
    score: 3,
  },
];
